### ISSUE TITLE
Team 1 NLP for comments

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#32]
This task is to use NLP to extract keywords and commonly used phrases from the commented text. there could also be some light sentiment analysis for the comments if we have time.

**Comment by mariakimheinert** [comment]
@dillam have you discussed this task with project managers of other groups who have to perform NLP as well?

**Comment by dillam** [comment]
@yeeunmariakim I have not.

**Comment by mariakimheinert** [comment]
@dillam then I think we should wait to address this issue until that discussion has been had.

**Comment by shafferz** [comment]
In lab, we discussed the ways to apply the NLP to the code. I believe it was @yeeunmariakim who proposed using topical analysis on both types of comment (single and multiple line), and sentiment analysis on the multiple line comments (due to their nature). @gkapfham encouraged us to push ahead far with the sentiment analysis, and I think we can get a lot of good to do from doing so.
