### ISSUE TITLE
Team 1 Sentiment analysis for single and multi-line comments

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#45]

**Comment by shafferz** [comment]
I remember working on sentiment analysis in 370, and am roughly familiar with how to use this. I would propose using the Natural Language Toolkit (nltk) python libraries for this. You can see examples and information related to that [here](http://www.nltk.org/api/nltk.sentiment.html#module-nltk.sentiment). It allows us to get a handle on the sentiment (negative, neutral, or positive) as percentages. It also provides a compound value that would indicate the strength, or intensity, of the analysis. These examples provided on [this page](http://www.nltk.org/howto/sentiment.html) highlights it best:

`This movie doesn't care about cleverness, wit or any other kind of intelligent humor.
compound: -0.1338, neg: 0.265, neu: 0.497, pos: 0.239,`
`There are slow and repetitive parts, BUT it has just enough spice to keep it interesting.
compound: 0.4678, neg: 0.079, neu: 0.735, pos: 0.186,`
`The script is not fantastic, but the acting is decent and the cinematography is EXCELLENT!
compound: 0.7565, neg: 0.092, neu: 0.607, pos: 0.301,`

I also would recommend converting the compound value to a "general intensity" by multiplying negative compound values by -1. The reason being that since we have a way to measure "negativity" with this toolkit, having a value that just measures general intensity (intensity, in this context, meaning how strong their feelings were) would be more useful and relevant.

**Comment by shafferz** [comment]
@yeeunmariakim and I will be starting research on sentiment analysis tools such at the Natural Language Toolkit, and will compare our results and (light) implementations by Friday, and by then we should have a solid idea of exactly how we're going to move forward and implement the functionality of this issue.

**Comment by mariakimheinert** [comment]
Feature added in PR #69.
